all: foo.c shared.c
	gcc -fPIC -c shared.c
	gcc -fPIC -c foo.c
ifeq (${CONF},LINUX)
	gcc -shared -o libshared.so shared.o foo.o
else
 ifeq (${CONF},WINDOWS)
	gcc -shared -o shared.dll shared.o foo.o
 endif
endif
