all: main.o main

main.o: main.c
	gcc -c main.c

main.exe: main.o shared.dll
ifeq (${CONF},WINDOWS)
	gcc -o main.exe main.c -L. -lshared
endif
main: main.c libshared.so
ifeq (${CONF},LINUX)
	gcc -o main main.c -L. -lshared
endif
